### ISSUE TITLE
Hello, how can I use this project?

### ISSUE THREAD

**Issue by hunkyu** [TixiaoShan/BGK_traversability_mapping#2]
I watched your youtube video and did a very good job. Is there a data set that can run this project?

**Comment by hunkyu** [comment]
I ran up your data set and found that the effect is very good. Is this data a way to make a map become dense after slam?

**Comment by TixiaoShan** [comment]
@hunkyu 
Yes, it is designed to make the map (that is generated from a sparse lidar) denser.

**Comment by TixiaoShan** [comment]
@hunkyu 
The dataset used in the video came from Stevens dataset on my Github.

**Comment by rock19970106** [comment]
hello,  could you provide the dataset and groundtruth in the simulated environment please?
